version: '3'
services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: django
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: